trigger:
- master

pool:
  name: 'PCS'

variables:
  solution: 'sajilo_cafe_backend.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  publishPath: '$(build.artifactStagingDirectory)\WebApp'

steps:
- task: NuGetCommand@2
  inputs:
    command: 'restore'

- task: UseDotNet@2
  inputs:
    version: '8.x'
    performMultiLevelLookup: true
    includePreviewVersions: true

# Clean the output folder
- script: |
    dotnet clean $(solution) -c $(buildConfiguration)
  displayName: 'Clean build output'

# Restore dependencies
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'

# Publish the project
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '-o $(publishPath) -c $(buildConfiguration) --no-restore -v diag'
    zipAfterPublish: false
    modifyOutputPath: false

# Publish build artifacts
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(publishPath)'
    ArtifactName: '$(Build.BuildNumber)'
    publishLocation: 'Container'
