trigger:
- master

pool:
  name: 'PCS'

variables:
  solution: 'sajilo_cafe_backend.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  publishPath: '$(build.artifactStagingDirectory)\WebApp'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'
    includePreviewVersions: false

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '$(solution)'
    feedsToUse: 'select'

- task: DeleteFiles@1
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)'
    Contents: '**/bin/**, **/obj/**'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '$(solution)'
    arguments: '--no-restore /p:TreatWarningsAsErrors=false'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    projects: '$(solution)'
    arguments: '-o $(publishPath) -v diag /p:TreatWarningsAsErrors=false'
    zipAfterPublish: false
    modifyOutputPath: false

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(publishPath)'
    ArtifactName: '$(Build.BuildNumber)'
    publishLocation: 'Container'
