trigger:
- master

pool:
  name: 'PCS'

variables:
  solution: 'sajilo_cafe_backend.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  publishPath: '$(build.artifactStagingDirectory)\WebApp'

steps:
- task: UseDotNet@2
  inputs:
    version: '8.x'
    includePreviewVersions: false

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '$(solution)'
    feedsToUse: 'select'



- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '-o $(publishPath) -v detailed'
    zipAfterPublish: false
    modifyOutputPath: false

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(publishPath)'
    ArtifactName: '$(Build.BuildNumber)'
    publishLocation: 'Container'