trigger:
- master

pool:
  name: 'PCS'

variables:
  solution: 'CAfe.App/CAfe.App.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  publishPath: '$(build.artifactStagingDirectory)\WebApp'

steps:
- task: UseDotNet@2
  displayName: use-dotnet
  inputs:
    packageType: 'sdk'
    version: '8.x'
    includePreviewVersions: true

- task: DotNetCoreCLI@2
  displayName: dotnet-restore
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

- script: |
    dotnet clean $(solution) -c $(buildConfiguration)
  displayName: 'Clean build output'

- task: DotNetCoreCLI@2
  displayName: dotnet-build
  inputs:
    command: 'build'
    projects: '$(solution)'
    arguments: '--no-restore -c $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: dotnet-publish
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '-o $(publishPath) -c $(buildConfiguration) --no-restore'
    zipAfterPublish: false
    modifyOutputPath: false

- task: PublishBuildArtifacts@1
  displayName: create-publish-artifact
  inputs:
    PathtoPublish: '$(publishPath)'
    ArtifactName: '$(Build.BuildNumber)'
    publishLocation: 'Container'
