// <auto-generated />
using System;
using Cafe.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cafe.Infrastructure.Migrations
{
    [DbContext(typeof(CafeContext))]
    [Migration("20241229202125_Inital")]
    partial class Inital
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("cafe")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cafe.Infrastructure.Domain.Modals.Cafe.CafeM", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<byte[]>("CafeLogo")
                        .HasColumnType("bytea")
                        .HasColumnName("cafelogo");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletedate");

                    b.Property<string>("EntryBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entryby");

                    b.Property<DateTime?>("EntryDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("entrydate");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lastupdated");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int?>("Subscriptionid")
                        .HasColumnType("integer")
                        .HasColumnName("subscriptionid");

                    b.HasKey("Id")
                        .HasName("pk_cafes");

                    b.HasIndex("Subscriptionid")
                        .HasDatabaseName("ix_cafes_subscriptionid");

                    b.ToTable("cafes", "cafe");
                });

            modelBuilder.Entity("Cafe.Infrastructure.Domain.Modals.Cafe.Subscription", b =>
                {
                    b.Property<int>("Subscriptionid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("subscriptionid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Subscriptionid"));

                    b.Property<DateTime?>("Createdat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<int>("Durationmonths")
                        .HasColumnType("integer")
                        .HasColumnName("durationmonths");

                    b.Property<bool?>("Isactive")
                        .HasColumnType("boolean")
                        .HasColumnName("isactive");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<string>("Subscriptionname")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subscriptionname");

                    b.HasKey("Subscriptionid")
                        .HasName("pk_subscriptions");

                    b.ToTable("subscriptions", "cafe");
                });

            modelBuilder.Entity("Security.Infrastructure.Domain.Menu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletedate");

                    b.Property<string>("EntryBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entryby");

                    b.Property<DateTime?>("EntryDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("entrydate");

                    b.Property<string>("HasChild")
                        .HasColumnType("text")
                        .HasColumnName("haschild");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lastupdated");

                    b.Property<string>("MUrl")
                        .HasColumnType("text")
                        .HasColumnName("murl");

                    b.Property<string>("MenuIcon")
                        .HasColumnType("text")
                        .HasColumnName("menuicon");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<double?>("OrderNo")
                        .HasColumnType("double precision")
                        .HasColumnName("orderno");

                    b.Property<Guid?>("Parent")
                        .HasColumnType("uuid")
                        .HasColumnName("parent");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("ToolTip")
                        .HasColumnType("text")
                        .HasColumnName("tooltip");

                    b.HasKey("Id")
                        .HasName("pk_menu");

                    b.ToTable("menu", "cafe");
                });

            modelBuilder.Entity("Security.Infrastructure.Domain.Role.Module", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletedate");

                    b.Property<string>("EntryBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entryby");

                    b.Property<DateTime?>("EntryDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("entrydate");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lastupdated");

                    b.Property<Guid?>("ModuleRoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("moduleroleid");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_module");

                    b.HasIndex("ModuleRoleId")
                        .HasDatabaseName("ix_module_moduleroleid");

                    b.ToTable("module", "cafe");
                });

            modelBuilder.Entity("Security.Infrastructure.Domain.Role.ModuleRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletedate");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("EntryBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entryby");

                    b.Property<DateTime?>("EntryDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("entrydate");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lastupdated");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid?>("UserRoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("userroleid");

                    b.HasKey("Id")
                        .HasName("pk_modulerole");

                    b.HasIndex("UserRoleId")
                        .HasDatabaseName("ix_modulerole_userroleid");

                    b.ToTable("modulerole", "cafe");
                });

            modelBuilder.Entity("Security.Infrastructure.Domain.Role.SubModule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletedate");

                    b.Property<string>("EntryBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entryby");

                    b.Property<DateTime?>("EntryDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("entrydate");

                    b.PrimitiveCollection<int[]>("Functions")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("functions");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lastupdated");

                    b.Property<Guid>("MenuId")
                        .HasColumnType("uuid")
                        .HasColumnName("menuid");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_submodule");

                    b.HasIndex("MenuId")
                        .HasDatabaseName("ix_submodule_menuid");

                    b.ToTable("submodule", "cafe");
                });

            modelBuilder.Entity("Security.Infrastructure.Domain.Role.SubModuleFunction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletedate");

                    b.Property<string>("EntryBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entryby");

                    b.Property<DateTime?>("EntryDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("entrydate");

                    b.PrimitiveCollection<int[]>("Functions")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("functions");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lastupdated");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("SubModuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("submoduleid");

                    b.Property<Guid?>("UserRoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("userroleid");

                    b.HasKey("Id")
                        .HasName("pk_submodulefunction");

                    b.HasIndex("SubModuleId")
                        .HasDatabaseName("ix_submodulefunction_submoduleid");

                    b.HasIndex("UserRoleId")
                        .HasDatabaseName("ix_submodulefunction_userroleid");

                    b.ToTable("submodulefunction", "cafe");
                });

            modelBuilder.Entity("Security.Infrastructure.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CafeMId")
                        .HasColumnType("uuid")
                        .HasColumnName("cafemid");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletedate");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("discriminator");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("EntryBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entryby");

                    b.Property<DateTime?>("EntryDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("entrydate");

                    b.Property<string>("IP")
                        .HasColumnType("text")
                        .HasColumnName("ip");

                    b.Property<bool?>("IsLoggedIn")
                        .HasColumnType("boolean")
                        .HasColumnName("isloggedin");

                    b.Property<DateTime?>("LastLoggedIn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lastloggedin");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lastupdated");

                    b.Property<DateTime?>("LogInExpireTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("loginexpiretime");

                    b.Property<string>("MAC")
                        .HasColumnType("text")
                        .HasColumnName("mac");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("UserStatus")
                        .HasColumnType("integer")
                        .HasColumnName("userstatus");

                    b.HasKey("Id")
                        .HasName("pk_user");

                    b.HasIndex("CafeMId")
                        .HasDatabaseName("ix_user_cafemid");

                    b.ToTable("user", "cafe");

                    b.HasDiscriminator().HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Security.Infrastructure.Domain.Users.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletedate");

                    b.Property<string>("EntryBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entryby");

                    b.Property<DateTime?>("EntryDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("entrydate");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lastupdated");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("userid");

                    b.HasKey("Id")
                        .HasName("pk_userrole");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_userrole_userid");

                    b.ToTable("userrole", "cafe");
                });

            modelBuilder.Entity("Security.Infrastructure.Domain.Users.UserStatusLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AuthBy")
                        .HasColumnType("text")
                        .HasColumnName("authby");

                    b.Property<string>("AuthDate")
                        .HasColumnType("text")
                        .HasColumnName("authdate");

                    b.Property<string>("AuthNo")
                        .HasColumnType("text")
                        .HasColumnName("authno");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletedate");

                    b.Property<string>("EntryBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entryby");

                    b.Property<DateTime?>("EntryDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("entrydate");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lastupdated");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("userid");

                    b.Property<string>("UserStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("userstatus");

                    b.HasKey("Id")
                        .HasName("pk_userstatuslog");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_userstatuslog_userid");

                    b.ToTable("userstatuslog", "cafe");
                });

            modelBuilder.Entity("Cafe.Infrastructure.Domain.Modals.Employees.Employee", b =>
                {
                    b.HasBaseType("Security.Infrastructure.Domain.Users.User");

                    b.Property<Guid>("CafeId")
                        .HasColumnType("uuid")
                        .HasColumnName("cafeid");

                    b.HasIndex("CafeId")
                        .HasDatabaseName("ix_user_cafeid");

                    b.HasDiscriminator().HasValue("Employee");
                });

            modelBuilder.Entity("Cafe.Infrastructure.Domain.Modals.Cafe.CafeM", b =>
                {
                    b.HasOne("Cafe.Infrastructure.Domain.Modals.Cafe.Subscription", "Subscription")
                        .WithMany("Caves")
                        .HasForeignKey("Subscriptionid")
                        .HasConstraintName("fk_cafes_subscriptions_subscriptionid");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("Security.Infrastructure.Domain.Role.Module", b =>
                {
                    b.HasOne("Security.Infrastructure.Domain.Role.ModuleRole", null)
                        .WithMany("Modules")
                        .HasForeignKey("ModuleRoleId")
                        .HasConstraintName("fk_module_modulerole_moduleroleid");
                });

            modelBuilder.Entity("Security.Infrastructure.Domain.Role.ModuleRole", b =>
                {
                    b.HasOne("Security.Infrastructure.Domain.Users.UserRole", null)
                        .WithMany("ModuleRoles")
                        .HasForeignKey("UserRoleId")
                        .HasConstraintName("fk_modulerole_userrole_userroleid");
                });

            modelBuilder.Entity("Security.Infrastructure.Domain.Role.SubModule", b =>
                {
                    b.HasOne("Security.Infrastructure.Domain.Menu", "Menu")
                        .WithMany()
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_submodule_menu_menuid");

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("Security.Infrastructure.Domain.Role.SubModuleFunction", b =>
                {
                    b.HasOne("Security.Infrastructure.Domain.Role.SubModule", "SubModule")
                        .WithMany()
                        .HasForeignKey("SubModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_submodulefunction_submodule_submoduleid");

                    b.HasOne("Security.Infrastructure.Domain.Users.UserRole", null)
                        .WithMany("SubModuleFunctions")
                        .HasForeignKey("UserRoleId")
                        .HasConstraintName("fk_submodulefunction_userrole_userroleid");

                    b.Navigation("SubModule");
                });

            modelBuilder.Entity("Security.Infrastructure.Domain.Users.User", b =>
                {
                    b.HasOne("Cafe.Infrastructure.Domain.Modals.Cafe.CafeM", null)
                        .WithMany("Users")
                        .HasForeignKey("CafeMId")
                        .HasConstraintName("fk_user_cafes_cafemid");
                });

            modelBuilder.Entity("Security.Infrastructure.Domain.Users.UserRole", b =>
                {
                    b.HasOne("Security.Infrastructure.Domain.Users.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_userrole_user_userid");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Security.Infrastructure.Domain.Users.UserStatusLog", b =>
                {
                    b.HasOne("Security.Infrastructure.Domain.Users.User", null)
                        .WithMany("StatusHistory")
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_userstatuslog_user_userid");
                });

            modelBuilder.Entity("Cafe.Infrastructure.Domain.Modals.Employees.Employee", b =>
                {
                    b.HasOne("Cafe.Infrastructure.Domain.Modals.Cafe.CafeM", "Cafe")
                        .WithMany("Employees")
                        .HasForeignKey("CafeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_cafes_cafeid");

                    b.Navigation("Cafe");
                });

            modelBuilder.Entity("Cafe.Infrastructure.Domain.Modals.Cafe.CafeM", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Cafe.Infrastructure.Domain.Modals.Cafe.Subscription", b =>
                {
                    b.Navigation("Caves");
                });

            modelBuilder.Entity("Security.Infrastructure.Domain.Role.ModuleRole", b =>
                {
                    b.Navigation("Modules");
                });

            modelBuilder.Entity("Security.Infrastructure.Domain.Users.User", b =>
                {
                    b.Navigation("StatusHistory");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Security.Infrastructure.Domain.Users.UserRole", b =>
                {
                    b.Navigation("ModuleRoles");

                    b.Navigation("SubModuleFunctions");
                });
#pragma warning restore 612, 618
        }
    }
}
