global using Microsoft.EntityFrameworkCore;
global using System.Linq.Expressions;
global using System.Text.Json;
global using App.Shared.Infrastructure;
global using Microsoft.AspNetCore.Mvc;
global using FluentValidation;
global using Microsoft.Extensions.DependencyInjection;
global using System.Reflection;
global using Security.App.Infrastructure.Domain.Users;